# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookLoginTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FacebookLoginTest
pod 'FBSDKCoreKit/Swift'
pod 'FBSDKLoginKit/Swift'

end
